#!/bin/bash -ex
cd `dirname $0`/src
rm -f $GOPATH/bin/deployer-go
GOBIN=$GOPATH/bin go install -race github.com/danielstutzman/sync-cloudfront-logs-to-bigquery/deployer-go/src/deployer-go
exec $GOPATH/bin/deployer-go
