#!/bin/bash -ex

if [ ! -e fixtures/discovery.json ]; then
  curl https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest > fixtures/discovery.json
fi

$GOPATH/bin/fake-big-query -discovery-json-path=$PWD/fixtures/discovery.json &
PID=$!

bq --api http://localhost:9090 ls
bq --api http://localhost:9090 query 'select count(*) from belugacdn_logs.visits'

kill $PID
